version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/mydatabase
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-vite-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: mysql:8.0
    container_name: my-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bo_mysoho
      MYSQL_USER: mysoho
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
